#!/bin/sh

if [ "$1" = 'configure' ]; then
    if [ -e /usr/bin/sbreload.real ]; then
        echo 'Original sbreload binary already backed up'
    else
        echo 'Creating backup of original sbreload binary...'
        mv /usr/bin/sbreload /usr/bin/sbreload.real
    fi

    echo 'Symlinking nosbreload to sbreload...'
    ln -sf /usr/bin/nosbreload /usr/bin/sbreload
fi
