#!/bin/sh

install_hook() {
  dpkg-divert --divert /usr/bin/sbreload.orig --package net.cadoth.nosbreload --rename --add /usr/bin/sbreload
}

if [ "$1" = "install" ]; then
  install_hook "$@"
fi

if [ "$1" = "upgrade" ] && [ "$2" = "0.1.0" ]; then
  echo 'Restoring original sbreload binary...'
  mv /usr/bin/sbreload.real /usr/bin/sbreload

  install_hook "$@"
fi
